### PR TITLE
test: Fix regex excape method

### PR DESCRIPTION
**Pull request by stepansergeevitch**
Fixed regex excaping logic to excape a question mark inside of it

### CODE REVIEW

**Review by ptiurin — COMMENTED** [review]
What had a broken regex before, Firebolt or Clojure itself?
AFAIK `??` is a lazy `?` operator so I'm not sure we can escape `?` this way. Does `\?` work at all?

**Comment by stepansergeevitch** [comment]
> What had a broken regex before, Firebolt or Clojure itself? AFAIK `??` is a lazy `?` operator so I'm not sure we can escape `?` this way. Does `\?` work at all?

This is for metabase implementation specifically. It explicitly tries to substitute values, and it's pretty dumb with where the question mark is. It just substitutes each one. It does replace `??` with `?` though. This happens sometimes, and sometimes it just passes prepared statement and parameters to a driver itself for a proper substitution. It's still a mystery for me how it decides

**Comment by ptiurin** [comment]
I'm a little worried about this change. Can we verify this works as intended by running Metabase and checking the query executed on Firebolt side? Specifically with question marks in regex.

**Comment by stepansergeevitch** [comment]
Validated with a test. Also tested this query against a string with a `?` symbol, it gets escaped

**Review by ptiurin — APPROVED** [review]
lgtm then

**Pull request merged**
